<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/doctormaster.Master" AutoEventWireup="true" CodeBehind="PendingAppointment.aspx.cs" Inherits="doctor.pendingappointment" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Pending Appointments</title>
    <style>
        .pending-container {
            max-width: 900px;
            margin: 50px auto;
            background-color: #fff;
            padding: 30px 40px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .pending-title {
            text-align: center;
            color: #2c3e50;
            margin-bottom: 40px;
        }

        .grid-wrapper {
            overflow-x: auto;
        }

        .GridView-d {
            width: 100%;
            border-collapse: collapse;
        }

        .GridView-d th,
        .GridView-d td {
            padding: 10px;
            text-align: left;
        }

        @media (max-width: 768px) {
            .pending-container {
                padding: 20px;
            }
        }
    </style>
    <link rel="stylesheet" href="/assets/css/grid-view.css"/>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="Cp3" runat="server">

    <div class="pending-container">
        <h1 class="pending-title">Pending Appointments</h1>

        <div class="grid-wrapper">
            <asp:GridView ID="pendingappointments" runat="server" CssClass="GridView-d"
                AutoGenerateSelectButton="True" 
                AutoGenerateDeleteButton="True"
                EnableViewState="False"
                OnRowCommand="update_appointment"
                OnRowDeleting="Delete_appointment"
                BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px"
                CellPadding="4" ForeColor="Black" GridLines="Vertical">

                <AlternatingRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />

            </asp:GridView>
        </div>
    </div>

</asp:Content>
