<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageClinic.aspx.cs" Inherits="DBProject.ManageClinic" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style>
        .outer {
            margin: 40px auto;
            max-width: 950px;
            padding: 30px;
            background-color: #fdfdfd;
            border-radius: 10px;
            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
            font-family: 'Segoe UI', sans-serif;
        }

        h4 {
            font-size: 20px;
            margin-bottom: 15px;
            font-weight: 600;
            color: #333;
        }

        .radio-group {
            margin-bottom: 25px;
        }

        .radio-group asp\:RadioButton {
            margin-right: 25px;
            font-size: 15px;
        }

        .search-box {
            margin-bottom: 30px;
        }

        .search-box input[type="text"] {
            padding: 8px 12px;
            border: 1px solid #ccc;
            border-radius: 6px;
            font-size: 14px;
            width: 250px;
            margin-right: 10px;
        }

        .search-box button,
        .search-box .btn {
            background-color: #4A90E2;
            color: white;
            border: none;
            padding: 8px 16px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 14px;
        }

        .search-box .btn:hover {
            background-color: #357ABD;
        }

        .msg-label {
            color: #cc0000;
            font-weight: bold;
            margin-top: 10px;
            display: block;
        }

        .gridview-style {
            width: 100%;
            border-collapse: collapse;
        }

        .gridview-style th {
            background-color: #4A90E2;
            color: white;
            font-weight: bold;
            padding: 10px;
        }

        .gridview-style td {
            background-color: #f0f8ff;
            padding: 8px;
            color: #333;
            border: 1px solid #ddd;
        }

        .gridview-style tr:nth-child(even) td {
            background-color: #e6f2ff;
        }

        .gridview-style tr:hover td {
            background-color: #d0e4f5;
        }

        .caption {
            font-size: 18px;
            font-weight: bold;
            color: #444;
            text-align: center;
            margin-bottom: 15px;
        }

        .mydiv {
            /* هذا الاسم قديم، العنصر في HTML اسمه ContentPlaceHolder1_mydiv */
        }

        /* تعديل جديد ل mydiv لتثبيته فوق الفوتر */
        #ContentPlaceHolder1_mydiv {
            position: fixed;
            bottom: 80px;
            right: 20px;
            background-color: #fff;
            padding: 15px 20px;
            border-radius: 10px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            z-index: 1050;
            max-width: 300px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
    </style>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form runat="server">
        <div class="outer">

            <h4>Select Category:</h4>
            <div class="radio-group">
                <asp:RadioButton ID="Doctor" GroupName="Catagory" runat="server" Text="Doctor"
                    AutoPostBack="true" OnCheckedChanged="RadioButton_CheckedChanged" Checked="true" />
                <asp:RadioButton ID="Patient" GroupName="Catagory" runat="server" Text="Patient"
                    AutoPostBack="true" OnCheckedChanged="RadioButton_CheckedChanged" />
                <asp:RadioButton ID="OtherStaff" GroupName="Catagory" runat="server" Text="Other Staff"
                    AutoPostBack="true" OnCheckedChanged="RadioButton_CheckedChanged" />
            </div>

            <div class="search-box">
                <asp:TextBox ID="txtSearch" runat="server" />
                <asp:Button Text="Search" runat="server" CssClass="btn" OnClick="Search_btn" />
            </div>

            <asp:Label ID="Msg" runat="server" CssClass="msg-label"></asp:Label>

            <asp:GridView ID="Manage"
                runat="server"
                AutoGenerateDeleteButton="True"
                AutoGenerateSelectButton="True"
                EnableViewState="False"
                OnRowDeleting="DeleteDoctor_Click"
                OnRowCommand="SelectCommand"
                CssClass="gridview-style"
                Caption="Doctors Table"
                CaptionAlign="Top"
                GridLines="None">
                <HeaderStyle />
                <RowStyle />
                <AlternatingRowStyle />
                <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            </asp:GridView>
        </div>

        <div style="display:inline-block; float:right; margin-right:10%" runat="server" id="mydiv"></div>

    </form>
</asp:Content>
